version: '3'

services:
  app:
    container_name: auth-service-app
    # image: bigsmilez/inconvenio-webshop:auth-service
    command: java -jar target/keycloak-springboot-microservice-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - KEYCLOAK_REALM=inconvenio
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth/
      - KEYCLOAK_SSL_REQUIRED=external
      - KEYCLOAK_RESOURCE=spring-boot-client
      - KEYCLOAK_CREDENTIALS_SECRET=2511b6af-1bd5-4dc1-bd20-f3d689c2d625
      - KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS=true
      - KEYCLOAK_BEARER_ONLY=true
      - SERVER_PORT=8089
      - PRODUCT_SERVER_URL=http://app:8085
    depends_on:
      - keycloak
      - keycloak_db
    networks:
      - backend
    restart: unless-stopped
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:15.0.2
    restart: always
    env_file: src/main/resources/keycloak.env
    depends_on:
      - keycloak_db
    volumes:
      - ./src/main/resources/import-this-realm.json:/tmp/realm.json

    ports:
      - "8080:8080"
    networks:
        - backend

  keycloak_db:
    container_name: database
    image: mariadb:10.3.26
    restart: always
    volumes:
      - keycloak_db_vol:/var/lib/mysql
    env_file:
      - src/main/resources/keycloak.env
    networks:
        - backend
networks:
  backend:
    driver: bridge
    external: true
    name: backend
volumes:
  keycloak_db_vol: