version: '3'
services:
  keycloak:
    image: jboss/keycloak
    command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/realm-export.json -Dkeycloak.import.strategy=overwrite
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - 8080:8080
    links:
      - postgres
    volumes:
      - ./realm-export.json:/realm-export.json
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
